repository_type: pipeline
lint:
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-variantcalling_logo_light.png
    - docs/images/nf-core-variantcalling_logo_light.png
    - docs/images/nf-core-variantcalling_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - assets/multiqc_config.yml
    - conf/igenomes.config
  files_unchanged:
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
    - lib/NfcoreTemplate.groovy
  nextflow_config:
    - manifest.name
    - manifest.homePage
